version: '3.8'

services:
  api-gateway:
    container_name: pbrs-api-gateway
    build:
      context: ./api-gateway
    ports:
      - "9005:5000"
    volumes:
      - ./api-gateway/src/main/python/app:/app # onlu for development
    environment:
      DATABASE_URL: postgresql://pbrs_manager:faw392k892@postgres:5432/pbrs
    depends_on:
      - user-service
    networks:
      - pbrs-network

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: pbrs
      POSTGRES_USER: pbrs_manager
      POSTGRES_PASSWORD: faw392k892
    ports:
      - "9006:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pbrs-network

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "9007:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - pbrs-network

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9008:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - pbrs-network

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "9009:2181"
    networks:
      - pbrs-network

#  user-service:
#    container_name: pbrs-user-service
#    build:
#      context: ./user-service
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pbrs
#      SPRING_DATASOURCE_USERNAME: pbrs_manager
#      SPRING_DATASOURCE_PASSWORD: faw392k892
#    volumes:
#      - ./user-service/src:/app/src # onlu for development
#    ports:
#      - "9010:8080"
#    depends_on:
#      - postgres
#    networks:
#      - pbrs-network
#
#  book-service:
#    container_name: pbrs-book-service
#    build:
#      context: ./book-service
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pbrs
#      SPRING_DATASOURCE_USERNAME: pbrs_manager
#      SPRING_DATASOURCE_PASSWORD: faw392k892
#    volumes:
#      - ./book-service/src:/app/src # onlu for development
#    ports:
#      - "9012:8080"
#    depends_on:
#      - postgres
#    networks:
#      - pbrs-network

  user-service:
    container_name: pbrs-user-service
    build:
      context: ./user-service
      dockerfile: Dockerfile-dev
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pbrs
      SPRING_DATASOURCE_USERNAME: pbrs_manager
      SPRING_DATASOURCE_PASSWORD: faw392k892
      SPRING_DEVTOOLS_RESTART_ENABLED: true
      SPRING_DEVTOOLS_LIVERELOAD_ENABLED: true
      GRADLE_USER_HOME: /home/gradle/.gradle
      GRADLE_OPTS: -Dorg.gradle.unsafe.watch-fs=true
    volumes:
      - ./user-service/src:/app/src # onlu for development
      - ./user-service/.gradle:/home/.gradle
    ports:
      - "9010:8080"
    depends_on:
      - postgres
    networks:
      - pbrs-network
    command: ["./gradlew", "bootRun", "--continuous"]

  book-service:
    container_name: pbrs-book-service
    build:
      context: ./book-service
      dockerfile: Dockerfile-dev
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pbrs
      SPRING_DATASOURCE_USERNAME: pbrs_manager
      SPRING_DATASOURCE_PASSWORD: faw392k892
      SPRING_DEVTOOLS_RESTART_ENABLED: true
      SPRING_DEVTOOLS_LIVERELOAD_ENABLED: true
      GRADLE_USER_HOME: /home/gradle/.gradle
      GRADLE_OPTS: -Dorg.gradle.unsafe.watch-fs=true
    volumes:
      - ./book-service/src:/app/src # onlu for development
      - ./book-service/.gradle:/home/.gradle
    ports:
      - "9012:8080"
    depends_on:
      - postgres
    networks:
      - pbrs-network
    command: ["./gradlew", "bootRun", "--continuous"]

volumes:
  postgres_data:
  jenkins_home:

networks:
  pbrs-network:
    name: pbrs-network